spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://korea-it.c7oe4ck0wkot.ap-northeast-2.rds.amazonaws.com:3306/todolist_db
    username: admin
    password: 1q2w3e4r!!